version: '3'

volumes:
    database-data:
networks:
    idea2app:

services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${AUTHING_APP_SECRET}
        volumes:
            - database-data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        networks:
            - idea2app
        restart: always
    data-service:
        depends_on:
            - postgres
        image: ideamall/data-service
        environment:
            - NODE_ENV=production
            - DATABASE_URL=postgres://postgres:${AUTHING_APP_SECRET}@postgres:5432/postgres
            - PORT=8080
        ports:
            - 8080:8080
        networks:
            - idea2app
        restart: always
    caddy:
        depends_on:
            - data-service
        image: caddy
        ports:
            - 80:80
            - 443:443
        networks:
            - idea2app
        command: caddy reverse-proxy --from example.com --to data-service:8080
